### ISSUE TITLE
A typo in the manuscript

### ISSUE THREAD

**Issue by bokveizen** [ai4co/gfacs#2]
Not sure here is a right place to report it, but there is a typo in Figure 3 in the manuscript.
I suppose the "leaned" here should be "learned".

https://arxiv.org/pdf/2403.07041.pdf

![image](https://github.com/ai4co/gfacs/assets/32029544/11a7542b-0030-474a-a64f-3cc484af4916)

**Comment by hyeok9855** [comment]
Thank you! We will fix it when we update our manuscript later.
